#!/usr/bin/env php
<?php declare(strict_types=1);

require_once dirname(__FILE__) . '/vendor/autoload.php';

use ScreenshotPages\Capture;
use ScreenshotPages\Helpers\Cli;
use ScreenshotPages\Helpers\Parameters\JSONParameters;

if (empty($argv[1]))
{
    Cli::error('Empty filename argument');
    die();
}

$capture = new Capture();
$capture->verbose = true;
$capture->use(new JSONParameters($argv[1]))->make();